### PR TITLE
This closes #231

### LINKED ISSUE #231: Update classifiers in setup file
As of https://github.com/pythad/nider/pull/230 nider supports latest versions of Python (3.6+). We need to update classifiers in setup file (https://github.com/pythad/nider/blob/master/setup.py#L56) so that PyPi shows correct versions on their index page as long as in github badge.

Screen Shot 2020-08-13 at 14 55 58

### PR DESCRIPTION
**Pull request by pandrey2003**
Confronted classifiers in `setup.py` to the Python versions in `tox.ini` and `.travis.yml`.

### CODE REVIEW

**Comment by pandrey2003** [comment]
Travis CI has failed as I used the old fork. Due to the simplicity of change, see no point in re-forking and creating one more pull request :D

**Comment by pythad** [comment]
Great, thanks!

**Comment by pythad** [comment]
Also you do not need to re-fork repo each time you want to make a change. You just need to sync your forked repo with upstream one when upstream changes. You can read more about it [here](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository).

**Comment by andrei-polukhin** [comment]
> Also you do not need to re-fork repo each time you want to make a change. You just need to sync your forked repo with upstream one when upstream changes. You can read more about it [here](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository).

Very obliged for the remark about re-forking. I am happy to feel I have gaps in my git skills :)

**Pull request merged**
